;TENDMP.CTL%001 - 05 OCT 71 - TO CREATE TENDMP.REL FOR USE
; WITH "COPY", AND A 48K PAPER-TAPE TENDMP FOR HARDWARE-READ-IN
; FROM THE PAPER TAPE READER OF THE PDP-10
;
;SUBMIT THIS CONTROL FILE WITH THE COMMAND
;  .QUEUE INP:=TENDMP.CTL/RESTART:1
;
;REQUIRED FILES:
; IN YOUR OWN AREA,
;	TENDMP.MAC
; IN THE STANDARD DISTRIBUTION AREA, [10,7], THE
; LATEST RELEASED VERSIONS OF
;	MACRO.SHR
;	CREF.SHR
;	TECO.SHR
;	DIRECT.SHR
;
; THE OUTPUTS OF THIS CONTROL FILE ARE
;	TENDMP.REL	;USABLE WITH "COPY"
;	TENDMP CREF LISTING, CORRESPONDING TO THE ABOVE REL FILE
;	PAPER TAPE OF 48K ABSOLUTE TENDMP, IN PDP10 HRI(RIM10B) FORMAT
;
;
;THE FOLLOWING ARE THE MANUAL ASSEMBLY INSTRUCTIONS FOR TENDMP
;
;ASSEMBLY INSTRUCTIONS:
;1. TO MAKE REL VERSION FOR LOADING WITH "COPY" PROGRAM
;	ASSEMBLE WITH PARAMETER "REL" = 1
;	AND NO ASSIGNMENT TO "CORE"
;
;2. TO MAKE ABSOLUTE PAPER TAPE VERSION, DEFINE CORE TO BE:
;	2	FOR 16K
;	4	FOR 32K
;	6	FOR 48K
;	10	FOR 64K
;	12	FOR 80K
;	14	FOR 96K, ETC
;	AND NO ASSIGNMENT TO "REL"
;
;	.R MACRO
;	PTP:_FTBOOT,TENDMP
;
;	WHERE FTBOOT.MAC HAS BEEN PREPARED WITH ASSIGNMENTS TO
;	PARAMETERS "CORE" AND "REL" AS APPROPRIATE
;
;MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (NOERROR) .GOTO A
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=TENDMP.MAC,MACRO.SHR[10,7],TECO.SHR[10,7],CREF.SHR[10,7]
.GOTO A
A:.
;MAKE TENDMP.REL FOR "COPY" AND THE CREF LISTING
.RUN DSK:TECO[10,7]
*EWFTBOOT.MACI
*REL==1		;SET FOR REL ASSEMBLY
*EX
.RUN DSK:MACRO[10,7]
*TENDMP,/C_FTBOOT,TENDMP
.RUN DSK:CREF[10,7]
*LPT:TENDMP_
;NOW MAKE THE PAPER TAPE OF 48K TENDMP
.RUN DSK:TECO[10,7]
*EWFTBOOT.MACI
CORE=6		;MODIFY THIS LINE FOR OTHER SIZES
*EX
.RUN DSK:MACRO[10,7]
*PTP:TENDMP_FTBOOT,TENDMP
;THIS OBJECT PROGRAM BEING AN EXEC MODE BOOTSTRAP, THERE IS
;NO WAY TO TEST IT UNDER BATCH, SO WE LET THAT PASS.
;
;TELL THE OPR WE WERE SUCCESSFUL
.PLEASE TENDMP SUCCESSFUL
;DELETE THE FTBOOT FILE, WHICH IS EXTRANEOUS NOW
.DELETE FTBOOT.MAC
